const Country = require('../models/country'); // Adjust the path to your model as needed

module.exports = async () => {
  try {
    // Delete all existing countries to start fresh
    await Country.deleteMany({});
    console.log('Deleted all existing countries.'.bgRed.white);

    const countries = [
      {"country_name": "Afghanistan", "flag": "🇦🇫", "code": "+93"},
      {"country_name": "Albania", "flag": "🇦🇱", "code": "+355"},
      {"country_name": "Algeria", "flag": "🇩🇿", "code": "+213"},
      {"country_name": "America", "flag": "🇺🇸", "code": "+1"},
      {"country_name": "Andorra", "flag": "🇦🇩", "code": "+376"},
      {"country_name": "Angola", "flag": "🇦🇴", "code": "+244"},
      {"country_name": "Argentina", "flag": "🇦🇷", "code": "+54"},
      {"country_name": "Armenia", "flag": "🇦🇲", "code": "+374"},
      {"country_name": "Australia", "flag": "🇦🇺", "code": "+61"},
      {"country_name": "Austria", "flag": "🇦🇹", "code": "+43"},
      {"country_name": "Azerbaijan", "flag": "🇦🇿", "code": "+994"},
      {"country_name": "Bahamas", "flag": "🇧🇸", "code": "+1-242"},
      {"country_name": "Bahrain", "flag": "🇧🇭", "code": "+973"},
      {"country_name": "Bangladesh", "flag": "🇧🇩", "code": "+880"},
      {"country_name": "Barbados", "flag": "🇧🇧", "code": "+1-246"},
      {"country_name": "Belarus", "flag": "🇧🇾", "code": "+375"},
      {"country_name": "Belgium", "flag": "🇧🇪", "code": "+32"},
      {"country_name": "Belize", "flag": "🇧🇿", "code": "+501"},
      {"country_name": "Benin", "flag": "🇧🇯", "code": "+229"},
      {"country_name": "Bhutan", "flag": "🇧🇹", "code": "+975"},
      {"country_name": "Bolivia", "flag": "🇧🇴", "code": "+591"},
      {"country_name": "Bosnia and Herzegovina", "flag": "🇧🇦", "code": "+387"},
      {"country_name": "Botswana", "flag": "🇧🇼", "code": "+267"},
      {"country_name": "Brazil", "flag": "🇧🇷", "code": "+55"},
      {"country_name": "Brunei", "flag": "🇧🇳", "code": "+673"},
      {"country_name": "Bulgaria", "flag": "🇧🇬", "code": "+359"},
      {"country_name": "Burkina Faso", "flag": "🇧🇫", "code": "+226"},
      {"country_name": "Burundi", "flag": "🇧🇮", "code": "+257"},
      {"country_name": "Cambodia", "flag": "🇰🇭", "code": "+855"},
      {"country_name": "Cameroon", "flag": "🇨🇲", "code": "+237"},
      {"country_name": "Canada", "flag": "🇨🇦", "code": "+1"},
      {"country_name": "Cape Verde", "flag": "🇨🇻", "code": "+238"},
      {"country_name": "Chad", "flag": "🇹🇩", "code": "+235"},
      {"country_name": "Chile", "flag": "🇨🇱", "code": "+56"},
      {"country_name": "China", "flag": "🇨🇳", "code": "+86"},
      {"country_name": "Colombia", "flag": "🇨🇴", "code": "+57"},
      {"country_name": "Comoros", "flag": "🇰🇲", "code": "+269"},
      {"country_name": "Congo", "flag": "🇨🇬", "code": "+242"},
      {"country_name": "Costa Rica", "flag": "🇨🇷", "code": "+506"},
      {"country_name": "Croatia", "flag": "🇭🇷", "code": "+385"},
      {"country_name": "Cuba", "flag": "🇨🇺", "code": "+53"},
      {"country_name": "Cyprus", "flag": "🇨🇾", "code": "+357"},
      {"country_name": "Czech Republic", "flag": "🇨🇿", "code": "+420"},
      {"country_name": "Denmark", "flag": "🇩🇰", "code": "+45"},
      {"country_name": "Djibouti", "flag": "🇩🇯", "code": "+253"},
      {"country_name": "Dominica", "flag": "🇩🇲", "code": "+1-767"},
      {"country_name": "Dominican Republic", "flag": "🇩🇴", "code": "+1-809"},
      {"country_name": "Ecuador", "flag": "🇪🇨", "code": "+593"},
      {"country_name": "Egypt", "flag": "🇪🇬", "code": "+20"},
      {"country_name": "El Salvador", "flag": "🇸🇻", "code": "+503"},
      {"country_name": "Equatorial Guinea", "flag": "🇬🇶", "code": "+240"},
      {"country_name": "Eritrea", "flag": "🇪🇷", "code": "+291"},
      {"country_name": "Estonia", "flag": "🇪🇪", "code": "+372"},
      {"country_name": "Eswatini", "flag": "🇸🇿", "code": "+268"},
      {"country_name": "Ethiopia", "flag": "🇪🇹", "code": "+251"},
      {"country_name": "Fiji", "flag": "🇫🇯", "code": "+679"},
      {"country_name": "Finland", "flag": "🇫🇮", "code": "+358"},
      {"country_name": "France", "flag": "🇫🇷", "code": "+33"},
      {"country_name": "Gabon", "flag": "🇬🇦", "code": "+241"},
      {"country_name": "Gambia", "flag": "🇬🇲", "code": "+220"},
      {"country_name": "Georgia", "flag": "🇬🇪", "code": "+995"},
      {"country_name": "Germany", "flag": "🇩🇪", "code": "+49"},
      {"country_name": "Ghana", "flag": "🇬🇭", "code": "+233"},
      {"country_name": "Greece", "flag": "🇬🇷", "code": "+30"},
      {"country_name": "Grenada", "flag": "🇬🇩", "code": "+1-473"},
      {"country_name": "Guatemala", "flag": "🇬🇹", "code": "+502"},
      {"country_name": "Guinea", "flag": "🇬🇳", "code": "+224"},
      {"country_name": "Guinea-Bissau", "flag": "🇬🇼", "code": "+245"},
      {"country_name": "Guyana", "flag": "🇬🇾", "code": "+592"},
      {"country_name": "Haiti", "flag": "🇭🇹", "code": "+509"},
      {"country_name": "Honduras", "flag": "🇭🇳", "code": "+504"},
      {"country_name": "Hungary", "flag": "🇭🇺", "code": "+36"},
      {"country_name": "Iceland", "flag": "🇮🇸", "code": "+354"},
      {"country_name": "India", "flag": "🇮🇳", "code": "+91"},
      {"country_name": "Indonesia", "flag": "🇮🇩", "code": "+62"},
      {"country_name": "Iran", "flag": "🇮🇷", "code": "+98"},
      {"country_name": "Iraq", "flag": "🇮🇶", "code": "+964"},
      {"country_name": "Ireland", "flag": "🇮🇪", "code": "+353"},
      {"country_name": "Israel", "flag": "🇮🇱", "code": "+972"},
      {"country_name": "Italy", "flag": "🇮🇹", "code": "+39"},
      {"country_name": "Jamaica", "flag": "🇯🇲", "code": "+1-876"},
      {"country_name": "Japan", "flag": "🇯🇵", "code": "+81"},
      {"country_name": "Jordan", "flag": "🇯🇴", "code": "+962"},
      {"country_name": "Kazakhstan", "flag": "🇰🇿", "code": "+7"},
      {"country_name": "Kenya", "flag": "🇰🇪", "code": "+254"},
      {"country_name": "Kiribati", "flag": "🇰🇮", "code": "+686"},
      {"country_name": "Korea, North", "flag": "🇰🇵", "code": "+850"},
      {"country_name": "Korea, South", "flag": "🇰🇷", "code": "+82"},
      {"country_name": "Kuwait", "flag": "🇰🇼", "code": "+965"},
      {"country_name": "Kyrgyzstan", "flag": "🇰🇬", "code": "+996"},
      {"country_name": "Laos", "flag": "🇱🇸", "code": "+856"},
      {"country_name": "Latvia", "flag": "🇱🇻", "code": "+371"},
      {"country_name": "Lebanon", "flag": "🇱🇧", "code": "+961"},
      {"country_name": "Lesotho", "flag": "🇱🇸", "code": "+266"},
      {"country_name": "Liberia", "flag": "🇱🇷", "code": "+231"},
      {"country_name": "Libya", "flag": "🇱🇾", "code": "+218"},
      {"country_name": "Liechtenstein", "flag": "🇱🇮", "code": "+423"},
      {"country_name": "Lithuania", "flag": "🇱🇹", "code": "+370"},
      {"country_name": "Luxembourg", "flag": "🇱🇺", "code": "+352"},
      {"country_name": "Madagascar", "flag": "🇲🇬", "code": "+261"},
      {"country_name": "Malawi", "flag": "🇲🇼", "code": "+265"},
      {"country_name": "Malaysia", "flag": "🇲🇾", "code": "+60"},
      {"country_name": "Maldives", "flag": "🇲🇻", "code": "+960"},
      {"country_name": "Mali", "flag": "🇲🇱", "code": "+223"},
      {"country_name": "Malta", "flag": "🇲🇹", "code": "+356"},
      {"country_name": "Marshall Islands", "flag": "🇲🇭", "code": "+692"},
      {"country_name": "Mauritania", "flag": "🇲🇷", "code": "+222"},
      {"country_name": "Mauritius", "flag": "🇲🇺", "code": "+230"},
      {"country_name": "Mexico", "flag": "🇲🇽", "code": "+52"},
      {"country_name": "Micronesia", "flag": "🇫🇲", "code": "+691"},
      {"country_name": "Moldova", "flag": "🇲🇩", "code": "+373"},
      {"country_name": "Monaco", "flag": "🇲🇨", "code": "+377"},
      {"country_name": "Mongolia", "flag": "🇲🇳", "code": "+976"},
      {"country_name": "Montenegro", "flag": "🇲🇪", "code": "+382"},
      {"country_name": "Morocco", "flag": "🇲🇦", "code": "+212"},
      {"country_name": "Mozambique", "flag": "🇲🇿", "code": "+258"},
      {"country_name": "Myanmar", "flag": "🇲🇲", "code": "+95"},
      {"country_name": "Namibia", "flag": "🇳🇦", "code": "+264"},
      {"country_name": "Nauru", "flag": "🇳🇷", "code": "+674"},
      {"country_name": "Nepal", "flag": "🇳🇵", "code": "+977"},
      {"country_name": "Netherlands", "flag": "🇳🇱", "code": "+31"},
      {"country_name": "New Zealand", "flag": "🇳🇿", "code": "+64"},
      {"country_name": "Nicaragua", "flag": "🇳🇮", "code": "+505"},
      {"country_name": "Niger", "flag": "🇳🇪", "code": "+227"},
      {"country_name": "Nigeria", "flag": "🇳🇬", "code": "+234"},
      {"country_name": "North Macedonia", "flag": "🇲🇰", "code": "+389"},
      {"country_name": "Norway", "flag": "🇳🇴", "code": "+47"},
      {"country_name": "Oman", "flag": "🇴🇲", "code": "+968"},
      {"country_name": "Pakistan", "flag": "🇵🇰", "code": "+92"},
      {"country_name": "Palau", "flag": "🇵🇬", "code": "+680"},
      {"country_name": "Panama", "flag": "🇵🇦", "code": "+507"},
      {"country_name": "Papua New Guinea", "flag": "🇵🇬", "code": "+675"},
      {"country_name": "Paraguay", "flag": "🇵🇾", "code": "+595"},
      {"country_name": "Peru", "flag": "🇵🇪", "code": "+51"},
      {"country_name": "Philippines", "flag": "🇵🇭", "code": "+63"},
      {"country_name": "Poland", "flag": "🇵🇱", "code": "+48"},
      {"country_name": "Portugal", "flag": "🇵🇹", "code": "+351"},
      {"country_name": "Qatar", "flag": "🇶🇦", "code": "+974"},
      {"country_name": "Romania", "flag": "🇷🇴", "code": "+40"},
      {"country_name": "Russia", "flag": "🇷🇺", "code": "+7"},
      {"country_name": "Rwanda", "flag": "🇷🇼", "code": "+250"},
      {"country_name": "Saint Kitts and Nevis", "flag": "🇰🇳", "code": "+1-869"},
      {"country_name": "Saint Lucia", "flag": "🇱🇨", "code": "+1-758"},
      {"country_name": "Saint Vincent and the Grenadines", "flag": "🇻🇨", "code": "+1-784"},
      {"country_name": "Samoa", "flag": "🇼🇸", "code": "+685"},
      {"country_name": "San Marino", "flag": "🇸🇲", "code": "+378"},
      {"country_name": "Sao Tome and Principe", "flag": "🇸🇹", "code": "+239"},
      {"country_name": "Saudi Arabia", "flag": "🇸🇦", "code": "+966"},
      {"country_name": "Senegal", "flag": "🇸🇳", "code": "+221"},
      {"country_name": "Serbia", "flag": "🇷🇸", "code": "+381"},
      {"country_name": "Seychelles", "flag": "🇸🇨", "code": "+248"},
      {"country_name": "Sierra Leone", "flag": "🇸🇱", "code": "+232"},
      {"country_name": "Singapore", "flag": "🇸🇬", "code": "+65"},
      {"country_name": "Slovakia", "flag": "🇸🇰", "code": "+421"},
      {"country_name": "Slovenia", "flag": "🇸🇮", "code": "+386"},
      {"country_name": "Solomon Islands", "flag": "🇸🇧", "code": "+677"},
      {"country_name": "Somalia", "flag": "🇸🇴", "code": "+252"},
      {"country_name": "South Africa", "flag": "🇿🇦", "code": "+27"},
      {"country_name": "South Sudan", "flag": "🇸🇸", "code": "+211"},
      {"country_name": "Spain", "flag": "🇪🇸", "code": "+34"},
      {"country_name": "Sri Lanka", "flag": "🇱🇰", "code": "+94"},
      {"country_name": "Sudan", "flag": "🇸🇩", "code": "+249"},
      {"country_name": "Suriname", "flag": "🇸🇷", "code": "+597"},
      {"country_name": "Sweden", "flag": "🇸🇪", "code": "+46"},
      {"country_name": "Switzerland", "flag": "🇨🇭", "code": "+41"},
      {"country_name": "Syria", "flag": "🇸🇾", "code": "+963"},
      {"country_name": "Taiwan", "flag": "🇹🇼", "code": "+886"},
      {"country_name": "Tajikistan", "flag": "🇹🇯", "code": "+992"},
      {"country_name": "Tanzania", "flag": "🇹🇿", "code": "+255"},
      {"country_name": "Thailand", "flag": "🇹🇭", "code": "+66"},
      {"country_name": "Timor-Leste", "flag": "🇹🇱", "code": "+670"},
      {"country_name": "Togo", "flag": "🇹🇬", "code": "+228"},
      {"country_name": "Tonga", "flag": "🇹🇴", "code": "+676"},
      {"country_name": "Trinidad and Tobago", "flag": "🇹🇹", "code": "+1-868"},
      {"country_name": "Tunisia", "flag": "🇹🇳", "code": "+216"},
      {"country_name": "Turkey", "flag": "🇹🇷", "code": "+90"},
      {"country_name": "Turkmenistan", "flag": "🇹🇲", "code": "+993"},
      {"country_name": "Tuvalu", "flag": "🇹🇻", "code": "+688"},
      {"country_name": "Uganda", "flag": "🇺🇬", "code": "+256"},
      {"country_name": "Ukraine", "flag": "🇺🇦", "code": "+380"},
      {"country_name": "United Arab Emirates", "flag": "🇦🇪", "code": "+971"},
      {"country_name": "United Kingdom", "flag": "🇬🇧", "code": "+44"},
      {"country_name": "United States", "flag": "🇺🇸", "code": "+1"},
      {"country_name": "Uruguay", "flag": "🇺🇾", "code": "+598"},
      {"country_name": "Uzbekistan", "flag": "🇺🇿", "code": "+998"},
      {"country_name": "Vanuatu", "flag": "🇻🇺", "code": "+678"},
      {"country_name": "Vatican City", "flag": "🇻🇦", "code": "+379"},
      {"country_name": "Venezuela", "flag": "🇻🇪", "code": "+58"},
      {"country_name": "Vietnam", "flag": "🇻🇳", "code": "+84"},
      {"country_name": "Yemen", "flag": "🇾🇪", "code": "+967"},
      {"country_name": "Zambia", "flag": "🇿🇲", "code": "+260"},
      {"country_name": "Zimbabwe", "flag": "🇿🇼", "code": "+263"},
    ]

    for (const country of countries) {
      const { code, country_name, flag } = country;

      // Check if a country with the same code and country_name already exists
      const existingCountry = await Country.findOne({ code, country_name });

      if (!existingCountry) {
        // If no duplicate, insert the new country
        await Country.create({ country_name, flag, code });
        // console.log(`Inserted country: ${country_name} with code ${code}`);
      } else {
        console.log(`Duplicate found for country: ${country_name} with code ${code}. Skipping insertion.`.bgYellow.black);
      }
    }

    console.log('Countries inserted successfully.');
  } catch (error) {
    console.error('Error while seeding countries:', error);
  }
};
